import {
  ClerkProvider,
} from '@clerk/nextjs'
import { Indie_Flower } from 'next/font/google'
import './globals.css'
import { dark } from '@clerk/themes'
import Navbar from '@/components/Navbar'
import { ThemeProvider } from '@/components/ThemeProvider'
import { Toaster } from "@/components/ui/sonner"


const caveat = Indie_Flower({
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({children}) {
  return (
        <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
     <html lang="en" className={caveat.className} suppressHydrationWarning>
        <body className={`antialiased font-bold`}>
            <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          <Navbar/>
          {children}
          <Toaster />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}